version: 2
jobs:
  build:
    workDir: /home/builder/docker-futurenda-base
    docker:
      - image: futurenda/buildpack:v1.29.0
    steps:
      - checkout

      - type: shell
        name: git submodule
        command: |
          git submodule sync
          git submodule update --init

      - setup_remote_docker

      - run: docker build -t futurenda/busybox-builder -f Dockerfile.builder .

      - run: docker run futurenda/busybox-builder tar -c -C /usr/src busybox | tar x

      - run: ./scripts/rootfs.sh

      - type: shell
        name: Docker Image
        command: |
          docker build -t futurenda/base .
          docker run -t futurenda/base busybox | head -1
          TAG=v$(cat package.json| grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]')-ci.$CIRCLE_BUILD_NUM
          echo $TAG
